version: "3.9"
services:
  server:
    build: .
    environment:
      - GENIUS_KEY
      - REDIS_ADDR=redis://redis:6379
      - RUST_LOG=tower_http=trace
    ports:
      - "8000:8000"
  redis:
    image: "redis:latest"
      